### ISSUE TITLE
Install GitSavvy commit themes globally 

### ISSUE THREAD

**Issue by aristidesfl** [divmain/GitSavvy#402]
Is there a easy way to install the themes globally so they work also when git command line in used instead of GitSavvy? Ideally they would stay up-to-date with the latest version from GitSavvy

**Comment by stoivo** [comment]
I am not really sure if I understand what you want? So many you can come with one clear example?

**Comment by aristidesfl** [comment]
When you use git from the command line, you commit, and sublime pops up to edit the message, which theme do you see?

**Comment by stoivo** [comment]
Aaa, so if I understand you correctly. You set you EDITOR to sublime with something like this: `export EDITOR='subl -wn'`. And now when do execute the command `$ git commit` from the terminal, sublime open with some syntax. And you would like it to be the same syntax as if you open the commit view from GitSavvy?

The syntax that GitSavvy is called `GitSavvy Make Commit`.
It look like this
```yaml
%YAML 1.2
---
# http://www.sublimetext.com/docs/3/syntax.html
name: GitSavvy Make Commit
hidden: true
scope: git-savvy.make-commit
contexts:
  main:
    - match: ^##.*
      comment: commit header
      scope: comment.git-savvy.make-commit
    - match: \@\w*
      comment: github username
      scope: constant.other.git-savvy.make-commit.github-username
    - match: '(\w+/\w+)?#[0-9]+'
      comment: issue
      scope: constant.other.git-savvy.make-commit.issue-ref
    - match: ^(?=diff --git a/)
      comment: diff section
      push:
        - meta_scope: meta.git-savvy.commit-diff
        - match: ^$
          pop: true
        - include: scope:source.diff

```

We set all GitSavvy syntaxes to be hidden so it doest disturb the user anything when trying to set syntax.
